<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="google-site-verification" content="<?= $CONFIG->get('GOOGLE_VERIFICATION') ?>">

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?= $CONFIG->get('GTM_TAG') ?>');</script>
    <!-- End Google Tag Manager -->

    <link rel="preload" href="/static/fonts/Righteous/Righteous-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/static/fonts/Ubuntu_Mono/UbuntuMono-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/static/fonts/Ubuntu_Mono/UbuntuMono-Bold.woff2" as="font" type="font/woff2" crossorigin>
    <!-- bundle.css is generated by build.sh from the individual CSS files - edit those, not this -->
    <link rel="stylesheet" href="<?=$CONFIG->get('CSS_PATH')."bundle.css?v=".$CONFIG->get('ASSET_VERSION')?>">

    <?php
    if ($page !== null)
    {
        switch ($page) {
            case 'home':
                ?>
                <meta name="description" content="Official homepage of OffTheGridCG">
                <?php
                break;
            case 'about':
                ?>
                <meta name="description" content="About me and my intressts.">
                <?php
                break;
            case 'projects':
                ?>
                <meta name="description" content="A selection list of my projects that I have or currently am working on. With links for more info.">
                <?php
                break;
            case 'contact':
                ?>
                <meta name="description" content="How to get in contact with me in various ways.">
                <?php
                break;
        }
    }
    else
    {
        ?>
        <meta name="description" content="Official homepage of OffTheGridCG">
        <?php
    }
    ?>

    <title>Website of OffTheGridCG</title>
</head>
